- type: playTimeTracker
  id: JobMetroResident

- type: playTimeTracker
  id: JobMachinist

- type: playTimeTracker
  id: JobBastard

- type: playTimeTracker
  id: JobSergeantKrasnyProspekt

- type: playTimeTracker
  id: JobFighterKrasnyProspekt
